version: "3.9"
services:
  gowon:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    depends_on:
      - mirrorball

  mirrorball:
    image: mirrorball
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
