version: 2

jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    steps:
      - run:
          name: Deploy
          command: |
            ssh root@$GOWON_HOST_IP "/bin/bash ./deploy.sh"
