version: 2

jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    steps:
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no root@$GOWON_HOST_IP "cd ./gowon && /bin/bash ./deploy.sh"
